### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by wlfans123** [NYAN-x-CAT/Lime-RAT#10]
Hello.

I want to see the network traffic without encrypting it.

So, I deleted the C_Encryption.vb file on the server and client.

And I modified the part that depends on the AES function.

After the modification, I used DownloadExecute.

Then, looking at the network traffic, an error occurs.

Is this normal?

Server -> Client Network packet:
```
RU-|'L'|http://www.freeimages.co.uk/galleries/res/images/feature_office.jpg|'L'|1.jpg|'N'|
```

Client -> Server Network packet:
```
MSG|'L'|Error! Index was outside the bounds of the array.|'N'|
```

![err](https://user-images.githubusercontent.com/41763490/43753394-80069ace-9a40-11e8-9330-395c8e5ce56b.PNG)

Modify source code:  [source.zip](https://github.com/NYAN-x-CAT/Lime-RAT/files/2264903/source.zip)
```

C:\Lime-RAT-master\Project\Server\Classes\S_Socket.vb	
C:\Lime-RAT-master\Project\Server\Forms\Main.vb	
C:\Lime-RAT-master\Project\Client\C_Commands.vb
C:\Lime-RAT-master\Project\Client\C_Socket.vb
```

Thanks.

**Comment by NYAN-x-CAT** [comment]
Hello sir
the index was outside the arrays means that there's a missing value which is right, it's a false bug.
because the client is searching for A(3) which doesn't exist unless you are updating payload from URL.
But thanks because I have found another bug, I forgot to add MSG listener in the server.
I will fix these issues now with 0.1.6.1 update, you can close this issue after testing the new update, meanwhile, it will be open
Regards.

**Comment by wlfans123** [comment]
@NYAN-x-CAT 

Hello.

The problem has been solved. :)

Network : 
![good](https://user-images.githubusercontent.com/41763490/43809006-bcf3fa08-9aea-11e8-9da5-28c182b89952.PNG)

In my opinion, it would be nice if Lime-RAT had the option to disable the AES option in Network.

Because, for the sake of testing.

Thanks.

**Comment by NYAN-x-CAT** [comment]
Hello,
I made this project to simulate real malwares so adding option "disable secure communication" is unusual option and makes none sense.

But the the main source code is available so users can modify anything just the way you did it.

Regards.

**Comment by wlfans123** [comment]
@NYAN-x-CAT 

Hello.

>I made this project to simulate real malwares so adding option "disable secure communication" is unusual option and makes none sense.

Yes. I agree.
But, Required to confirm errors in the test process.
Developers can use live debugging, but ordinary users are hard to find bugs.

>But the the main source code is available so users can modify anything just the way you did it.

Yes. Developers can modify and use programs.
However, in my opinion, developers are not the only ones using this program.
Ex) QA, Network Engineer, System Engineer, general user who needs to test.

Thanks.
