### ISSUE TITLE
PasteBin

### ISSUE THREAD

**Issue by EN1GMA4** [NYAN-x-CAT/Lime-RAT#13]
How can i change pastebin link to normal Ip and port type? cause when i don't have network and want to test it need to download pastebin string if you can help me with it or modify a private source for me to enable that feature i will be so glad.

**Comment by NYAN-x-CAT** [comment]
Hello @Alpha-c0d3r 

You can test it without internet using **debug** compiler.

If you check class **C_Socket** you will find that I insert a direct IP:PORT in debug compiler.

![](https://i.imgur.com/sz0LHc8.png)

So you can just put your IP or DNS And also edit **C_Settings** before compile.

I can't do private source nor teaching you VB.NET, And to be honest, This is very weird request...

Regards.

**Comment by EN1GMA4** [comment]
how to make it c_settings.host = the pastebin.fied and c_settings.port = the port field?
