### ISSUE TITLE
Put change log

### ISSUE THREAD

**Issue by EN1GMA4** [NYAN-x-CAT/Lime-RAT#14]
Where is changelog of v0.1.7 that u added 5 min ago

**Comment by OpsecGuy** [comment]
what's new in 1.7 version?

**Comment by EN1GMA4** [comment]
Edit: 0.1.7 :V

**Comment by NYAN-x-CAT** [comment]
Hello @Alpha-c0d3r  @MaGicSuR 
I added changelog.

**Comment by EN1GMA4** [comment]
Where

**Comment by NYAN-x-CAT** [comment]
In release section.
