### ISSUE TITLE
Port 8989 always closed

### ISSUE THREAD

**Issue by emans841** [NYAN-x-CAT/Lime-RAT#15]
Port 8989 closed despite window firewall opened and port 8989 opened on canyouseeme.com
What could be the issue?
Am I the only one experiencing this?

**Comment by NYAN-x-CAT** [comment]
Hello @emans841 

> Am I the only one experiencing this?
**unfortunately, yes**

You can always use another open port, Also make 100% sure that you have a right setup for port forwarding and firewall exception

regards.

**Comment by emans841** [comment]
Since am not the only one experiencing this, will you look into this?
