### ISSUE TITLE
Version 0.1.7.3D had Upload Execute problems are they fixed?

### ISSUE THREAD

**Issue by mixedeffects** [NYAN-x-CAT/Lime-RAT#16]
Just asking, bc the problems only appear when I tested them on another computer and not on localhost?
When uploading from disk, the application won't run.

**Comment by NYAN-x-CAT** [comment]
Hello @mixedeffects 
Please use the latest version to avoid these problems.

**Comment by mixedeffects** [comment]
alright, ty.
