### ISSUE TITLE
Downloader not working

### ISSUE THREAD

**Issue by BlueRosee** [NYAN-x-CAT/Lime-RAT#17]
Hey,
When I tried adding direct download link to downloader part of RAT and tested client out, it gets error cannot start or run due to incompatibility with 64-bit windows, but once I try running exe directly it works.

**Comment by NYAN-x-CAT** [comment]
Hello @BlueRosee 

Are you trying to check run once?
URL is direct? example [http://www.mywebsite.com/client.exe]

**Comment by BlueRosee** [comment]
Yes, url is direct. And I tried both with and without run once, and got same result.

**Comment by NYAN-x-CAT** [comment]
Can you please try this URL without run once?

http://mirror2.internetdownloadmanager.com/idman631build3.exe

it's safe, it's IDM. Tell me if it works.

**Comment by BlueRosee** [comment]
It's working with this installer, and I now no longer even get an error with .exe built in Visual Studio but nothing happens.

**Comment by NYAN-x-CAT** [comment]
If the IDM worked, It means you are doing something wrong.
1. make sure the URL is direct
2. make sure the downloader is not detected by AV

**Comment by BlueRosee** [comment]
I thought about AV as well, so I turned all AV and firewall/defender. Could it be because I'm using online file hosting? Once I uploaded it I right clicked on download button and copy link location and pasted it in the field. Also I shouldn't be wrong link, as in the error it states name of the file, so it managed to download it just couldn't execute. Here's example of error I'm getting:
![capture](https://user-images.githubusercontent.com/42718160/44630577-43cfc300-a94f-11e8-9ec8-33d221655d05.PNG)

**Comment by NYAN-x-CAT** [comment]
It would be so helpful if I could get the uploader host domain or your sample URL.

**Comment by BlueRosee** [comment]
https://cdn-01.anonfile.com/u3ba0eg0b3/1bffd5a7-1535302255/DUCSetup_v4_1_1.exe

**Comment by NYAN-x-CAT** [comment]
This website doesn't give you direct URL all the time. Only gives you direct URL once.
As I told you above, You need to make sure that URL is direct.
You may test another uploader host, and then please close this issue. 

Regards.

**Comment by BlueRosee** [comment]
I tried few other sites and still nothing, could you recommend me some that do provide direct link?

**Comment by TheRealPolatic** [comment]
Just upload it on your own host which you can get for like 3$ a month or less.
No scanning, no distributing, allows exe's and you can even host sites with it.

**Comment by NYAN-x-CAT** [comment]
Make sure you uncheck run once.
Ir you can use like what @TheRealPolatic  says
