### ISSUE TITLE
Bypassing the anti-virus software, what should I do?

### ISSUE THREAD

**Issue by lhackercoco** [NYAN-x-CAT/Lime-RAT#18]
I'm trying to compile the program, but the generated EXE was killed by antivirus software.
Is there any good way to avoid this problem?
Thank you for the wonderful program. I like it very much.

**Comment by NYAN-x-CAT** [comment]
hello @18281706312 

You can temporarily disable av while you testing it

**Comment by lhackercoco** [comment]
Hello, when I was testing penetration, the target machine had anti-virus software, and I was like to know how not to be checked out by anti-virus software for this project.

At 2018-08-28 12:37:11, "NYAN CAT" <notifications@github.com> wrote:


hello @18281706312

You can temporarily disable av while you testing it

**Comment by NYAN-x-CAT** [comment]
It's a malware project, it will be detected by AV.

**Comment by lhackercoco** [comment]
I know, but can't you think of a way to prevent him from being detected?

At 2018-08-29 16:04:26, "NYAN CAT" <notifications@github.com> wrote:


It's a malware project, it will be detected by AV.

**Comment by NYAN-x-CAT** [comment]
I want it to be detected so people doesn't abuse it.
Thanks for testing limerat.

**Comment by lhackercoco** [comment]
我晕，这真是一个伤悲的故事

At 2018-08-29 16:17:03, "NYAN CAT" <notifications@github.com> wrote:


I want it to be detected so people doesn't abuse it.
Thanks for testing limerat.

**Comment by lhackercoco** [comment]
I feel dizzy. This is a sad story.

At 2018-08-29 16:17:03, "NYAN CAT" <notifications@github.com> wrote:


I want it to be detected so people doesn't abuse it.
Thanks for testing limerat.
