### ISSUE TITLE
Crashes after pressing the start button

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#19]
The program crashes immediately after I press the start button. here is the message 
![image](https://user-images.githubusercontent.com/36313151/44901186-5bbc9380-ad0f-11e8-8397-381b2fb700a1.png)

Windows 7 Ultimate x64 (VMware)
4GB RAM

**Comment by NYAN-x-CAT** [comment]
Hello @MikeTHEPro 

I'm using the same, win7 64bit. Did you delete any file inside "LimeRAT v0.1.8.1" folder?

**Comment by R3verseCha0s** [comment]
![image](https://user-images.githubusercontent.com/36313151/44901894-3a5ca700-ad11-11e8-8b8a-2f4da2d66672.png)
after opening it 2-3 times it finally opens

**Comment by MikeTHEPro** [comment]
btw i am the guy we talked yesterday on discord

**Comment by NYAN-x-CAT** [comment]
I will fix it next update, Thanks

**Comment by R3verseCha0s** [comment]
you found the issue?

**Comment by R3verseCha0s** [comment]
if i can help a bit it happens each time you restart your pc
