### ISSUE TITLE
Cannot Add Normal Form 

### ISSUE THREAD

**Issue by KronosCrown** [NYAN-x-CAT/Lime-RAT#2]
If we need to add a non modal Form  using  simply this:
```
Dim Form As New Form4
  Form.Show()
```
It would simply Show a non responding Form  if i add 
`Form.ShowDialog()  `
it works but it wont get all the features as  a non modal Form how can i make it work as normal  .Show() ?

To Be More Specific The issue is in the following in the file:

Form1.vb

When it receves the message from the client it wont open the any kind of not Modal Form it would just get stuck on Loading and not Responding so if i do:

```
 Private Sub S_Data(ByVal u As USER, ByVal b() As Byte) Handles S.Data
        Dim DATA As String() = Split(BS(b), RKEY)
        Try
            Select Case DATA(0)
Case "ANY"
        Dim Form As New Form4
              Form.Show()
```
Form.Show() would get stuck seems like if some loop is running so it blocks the form to run 
Please look at your code and see what is wrong
Best Regards

**Comment by NYAN-x-CAT** [comment]
Because there is a bug in class SK. however, it's too late fix it because I'm already doing a new update, I may release it in few days.
