### ISSUE TITLE
trying to access A: drive with no reason

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#20]
when i installed it in my friend's pc (he knew that, nothing illegal) he reported to me seeing errors from trying to access  A: drive nothing was connected there.

![image](https://user-images.githubusercontent.com/36313151/44913317-a9e48d80-ad35-11e8-8697-62cbe56b1588.png)
 P.S sorry its in greek

**Comment by NYAN-x-CAT** [comment]
Thanks for reporting, Will fix next version
