### ISSUE TITLE
Clipper

### ISSUE THREAD

**Issue by dmouse207** [NYAN-x-CAT/Lime-RAT#21]
can you check seems not to be working on my side
windows 10 pro

**Comment by TheRealPolatic** [comment]
Did you update the clients to the latest version?

**Comment by NYAN-x-CAT** [comment]
Hello @dmouse207 
You need to insert a valid BTC address, And you need to copy a valid BTC address

**Comment by dmouse207** [comment]
yes i set correct btc address while setting and tried to copy paste other btc address to check if it works.
and i used BETA mode the latest binary

**Comment by NYAN-x-CAT** [comment]
I did the same exact thing, and it worked...
please take a moment to read the source code

https://github.com/NYAN-x-CAT/Lime-RAT/blob/master/Project/Client/C_BTC.vb
