### ISSUE TITLE
*32 on task manager

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#23]
so i checked the process on task manager and it had a *32 after it

![default](https://user-images.githubusercontent.com/36313151/45234504-9bbae200-b2de-11e8-8426-77e49505df8d.png)

**Comment by NYAN-x-CAT** [comment]
Because you are using "LimeRAT v1.8.2 - BETA TESTER"
Which makes 32bit stub. You can change it on visual studio.

**Comment by R3verseCha0s** [comment]
I have 1.8.2 C version

**Comment by NYAN-x-CAT** [comment]
Yes, I know. That's what I just said.

Any bug with this version?

**Comment by R3verseCha0s** [comment]
Nothing so far when the next version is coming? Also please do my request on the downloader in the other project
