### ISSUE TITLE
Same PC showing 2 times on the gui

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#26]
Hello, as a tester of v0.1.8.2C i have found that sometimes the same pc is showed 2 or 3 times to the gui

**Comment by NYAN-x-CAT** [comment]
Hello @MikeTHEPro 
Yes I know about this issue, will fix it soon
Thanks

**Comment by NYAN-x-CAT** [comment]
This should be fixed by using the latest version
