### ISSUE TITLE
Password stealer doesnt work at all 

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#27]
The password doesnt work at all i open the plugin gui and there is nothing there. the client is running as admonistrator on windows 10 x64
Looks like this:
![default](https://user-images.githubusercontent.com/36313151/45300869-2c303700-b518-11e8-89df-a83724076c38.png)

**Comment by TheRealPolatic** [comment]
Are you sure the machine even has passwords stored? You could check with another rat or manually typing in a website and saving the creds

**Comment by gali313** [comment]
![screenshot_256](https://user-images.githubusercontent.com/31598764/45503548-5e0ffa80-b7b1-11e8-8ca6-cdcaa49eb63c.png)

it's work in my system, i'm using RDP>>virtualbox with windows 7 32bit

**Comment by NYAN-x-CAT** [comment]
Thank you @gali313 for your feedback.
