### ISSUE TITLE
Bug Still Not Fixed on Update

### ISSUE THREAD

**Issue by KronosCrown** [NYAN-x-CAT/Lime-RAT#3]
I reviewed the code but the bug is  not yet fixed to verify i just edited the Form1.vb from D.ShowDialog() to Show() 

```
                 'fix
                    D.ListView1.AutoResizeColumns(ColumnHeaderAutoResizeStyle.HeaderSize)
                    D.Show()
```
If you will fix it i will help yo adding the Remote Desktop ;)

**Comment by NYAN-x-CAT** [comment]
Hello, the update is a better connection between client and server.
for your issue, I fixed it
