### ISSUE TITLE
Miner options

### ISSUE THREAD

**Issue by Jh0nW1cK** [NYAN-x-CAT/Lime-RAT#30]
The miner works well, these are some possible improvements. 

The miner does not install on the client, so I have to run it from the server every time the system is rebooted. 

In addition it is not hidden in the task manager which makes it easily detectable by the user.

**Comment by R3verseCha0s** [comment]
This was in my mind. 
I think it should like close itself when task manager is open, have an option to go 100% when the user idles for some amount of time, it should install in the client, show the hashrate of every user on the panel, and maybe in the future GPU support? There are many open source GPU miner for both AMD and NVIDIA 

AMD GPU:
https://github.com/xmrig/xmrig-amd
NVIDIA GPU:
https://github.com/xmrig/xmrig-nvidia

P.S: You might want to add a stratum proxy, cause some pools ban accounts with more than 25 connections at the same time, so the proxy would make mining more efficient. And not bannable. 
https://github.com/xmrig/xmrig-proxy

**Comment by Jh0nW1cK** [comment]
Of course, the GPU mining option would be great.

**Comment by R3verseCha0s** [comment]
of course, it would be
also using a proxy would make mining more efficient thus more profitable 
because all connections are gathered up in a pc then sent to pool

**Comment by Jh0nW1cK** [comment]
You can install xmrig-proxy in a Vps, it would help that the option "use client ID as passw" will work to differentiate the miners.

**Comment by Jh0nW1cK** [comment]
In the miner, the option to use user ID as password does not work. 
Xmrig-proxy assigns the User field as ID instead of the password field. 
Therefore all the miners appear as one only in the proxy or pool.
