### ISSUE TITLE
Download and execute

### ISSUE THREAD

**Issue by Jh0nW1cK** [NYAN-x-CAT/Lime-RAT#31]
I do not know if this function is already running like this... 
download the payload and execute it in memory without dropping it on the disk and without encrypting the payload? 

Same as Lime Downloader.

**Comment by NYAN-x-CAT** [comment]
No, it will write it to disk then run it

**Comment by Jh0nW1cK** [comment]
If it were executed directly in memory, it would be a major improvement.
