### ISSUE TITLE
Some suggestions for improvement

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#32]
1. Add and ability to edit the regedit from the program without any popup (maybe add the ability to load a .reg file)
2. add a feature that can track cpu/ram usage in a whole (like task manager)
3. ability to change settings like, beeing able to turn spreading on/off, pastebin link etc(edited)
4. maybe the ability to see how much h/s a user has when he is mining
5. maybe add a feature that auto updates the ip on pastebin (idk if this is possible, but i think its possible thru API)
If these ever happen it would be a massive update

**Comment by Jh0nW1cK** [comment]
6. Command line as admin
7. Download and execute payload directly in memory
8. Description of the user's active window

**Comment by MikeTHEPro** [comment]
> 6. Command line as admin
> 7. Download and execute payload directly in memory
