### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by PDWR** [NYAN-x-CAT/Lime-RAT#34]
Bro please help me, I followed your steps ,  tried serial times ,but anytime go error ,I think it's a good software to learn ,can you record  some videos to show how to build it ?

**Comment by NYAN-x-CAT** [comment]
Hello @PDWR 

Please give us more details.

**Comment by PDWR** [comment]
![1](https://user-images.githubusercontent.com/31816249/45594385-655f2000-b9cc-11e8-9f77-1b2aa6f4eafd.png)
![2](https://user-images.githubusercontent.com/31816249/45594386-655f2000-b9cc-11e8-8eab-b14efdf7f93f.png)
![3](https://user-images.githubusercontent.com/31816249/45594387-65f7b680-b9cc-11e8-9c8a-5e84188ad307.png)
this is my steps , I can't build the exe file! I have no idea to solve it ! Please Help!

**Comment by R3verseCha0s** [comment]
Bro add me on discord and I'll help you with any issue the Developer is busy.
My discord is: Florid1995#4983

**Comment by gali313** [comment]
this is my step for build LR
![lime1](https://user-images.githubusercontent.com/31598764/45598175-aaea1000-ba01-11e8-9809-5eb1644df28b.png)
![lime 2](https://user-images.githubusercontent.com/31598764/45598171-a9204c80-ba01-11e8-8460-0945f62a127e.png)
![lime 3](https://user-images.githubusercontent.com/31598764/45598172-a9b8e300-ba01-11e8-90fa-0b6dfb24870b.png)
![lime 4](https://user-images.githubusercontent.com/31598764/45598173-a9b8e300-ba01-11e8-955e-3e59ac7338c6.png)
![lime 5](https://user-images.githubusercontent.com/31598764/45598174-aa517980-ba01-11e8-94cf-15779c4aa82a.png)

**Comment by NYAN-x-CAT** [comment]
Hello @PDWR 
Did you follow up @gali313  steps?

**Comment by PDWR** [comment]
@gali313 thank you for your steps，I tried your steps twice ,but error again , the same errors, did you work on vmware?

**Comment by PDWR** [comment]
@NYAN-x-CAT Bro , I follow up @gali313  steps ,but it goes error again?  I installed the .net4.0 and .net 2.0 framework ,did I miss anything the project need ?

**Comment by gali313** [comment]
> @gali313 thank you for your steps，I tried your steps twice ,but error again , the same errors, did you work on vmware?

i'm using vps (vultr) 
here my installation details 

![screenshot_266](https://user-images.githubusercontent.com/31598764/45626935-ef85b200-baba-11e8-9ef7-d009e32c5862.png)
![screenshot_267](https://user-images.githubusercontent.com/31598764/45626937-f01e4880-baba-11e8-976f-195189f103d4.png)
![screenshot_268](https://user-images.githubusercontent.com/31598764/45626938-f0b6df00-baba-11e8-91b0-e4adc59ed0db.png)
![screenshot_269](https://user-images.githubusercontent.com/31598764/45626940-f0b6df00-baba-11e8-93ea-c43c40318210.png)
![screenshot_270](https://user-images.githubusercontent.com/31598764/45626941-f14f7580-baba-11e8-9b2d-0452b099a7cb.png)
![screenshot_271](https://user-images.githubusercontent.com/31598764/45626942-f1e80c00-baba-11e8-934b-d2f8c7cebffc.png)
![screenshot_272](https://user-images.githubusercontent.com/31598764/45626943-f3193900-baba-11e8-8cbc-c692b0830c95.png)
![screenshot_273](https://user-images.githubusercontent.com/31598764/45626944-f3b1cf80-baba-11e8-8390-1facee2b246b.png)

**Comment by PDWR** [comment]
@gali313 wow  bro , your vps is so powerful, I only install the .net desktop development on my computer, I will try to install the other installation details like your vps and try again (tomorrow)!

**Comment by YungFrikandelbroodje** [comment]
You can compile it on your pc and then transfer it to your vps.
Or you just download the release version.

**Comment by gali313** [comment]
> @gali313 wow bro , your vps is so powerful, I only install the .net desktop development on my computer, I will try to install the other installation details like your vps and try again (tomorrow)!

i bought cheap account with $105 balance , i need for download n upload some stuff also compile some application :-)

happy coding dude and have a nice day.
