### ISSUE TITLE
Remote Doesn't work at all

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#35]
the Remote desktop feature doesn't work.
Keyboard and mouse option work well, but the remote screen, is basically stuck on this gray screen
![image](https://user-images.githubusercontent.com/36313151/45754654-e3b5ff00-bc24-11e8-8f5c-1afbc514b161.png)

**Comment by Jh0nW1cK** [comment]
How many customers have you tried? Is it possible that the client's screen is blocked?
