### ISSUE TITLE
The parameter is not valid

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#36]
My logs are full of this error. I think it translayes to something like "The parameter is not valid"

![image](https://user-images.githubusercontent.com/36313151/45764901-6d24fb80-bc3c-11e8-83a2-52c2202d8b78.png)

**Comment by NYAN-x-CAT** [comment]
.
Are you using github version and latest stub version? When did you get this error?

**Comment by R3verseCha0s** [comment]
I was using 0.1.8.4 you send on discord

**Comment by R3verseCha0s** [comment]
it fixed itself somehow
