### ISSUE TITLE
Stability and connection problems

### ISSUE THREAD

**Issue by Jh0nW1cK** [NYAN-x-CAT/Lime-RAT#37]
I have tested v0.1.8.4 with 10 clients and the problem persists.
I close the server and when opening it only 1 client is connected, in some cases the client never connects.
I have checked the connections of the process with netstat, in two clients there is a connection through port 443 to an IP of one proxy (cloudflare) and another one to pastebin, both for the same process...

https://m.imgur.com/a/kmcdEU2

**Comment by NYAN-x-CAT** [comment]
I would like to have more information. for your own privacy, please e-mail me :~
* client stub version
* pastebin url
* builder settings
* windows version on server side and client side
* when you close it, you mean close by press X button?

**Comment by Jh0nW1cK** [comment]
The appendix version is 0.1.8.4. 

I check the pastebin URL from the constructor and it is valid. 

I have tried with all the configurations of the constructor, in .net 2 and 4.

The windows versions in the client are 2003, xp, 7, 2008, 2012 and 2016. 

Yes, pressing the X button.

**Comment by NYAN-x-CAT** [comment]
Hello @Jh0nW1cK 

I think this should fix it. But you may have to wait about 1 minute for the client.exe to connect back after you close LimeRAT.exe .
https://www.sendspace.com/file/5hd9mn
Please, Try it and give me feedback as soon as possible.

Thanks

**Comment by Jh0nW1cK** [comment]
Hi @NYAN-x-CAT

Yes, it has been fixed. 

Can I know where the fault was?

**Comment by NYAN-x-CAT** [comment]
Hi @Jh0nW1cK 

I will explain it in a simple way. the client doesn't know that server is disconnected, so I added ping method to ping server repeatedly.

Also, I released it. you can download the official version.

**Comment by Jh0nW1cK** [comment]
@NYAN-x-CAT

I understand, thank you.
