### ISSUE TITLE
помогите мне

### ISSUE THREAD

**Issue by warese32** [NYAN-x-CAT/Lime-RAT#38]
https://pastebin.com/
как сделать эту url для bild ?
Help mi
или как сделать через noip dns чтобы работала программа 
пожалуйста у меня динамический ip

**Comment by YungFrikandelbroodje** [comment]
Put your IP in ( no DNS)and then enter the raw pastebin URL in lime.

You dont have to do anything with DNS's

**Comment by warese32** [comment]
мой ip меняется всегда как это сделать не понимаю 
я с dns делал понимаю объясние пожалуйста по подробней что куда

**Comment by warese32** [comment]
программа показывает что индекс находился вне границ массива 
как исправить это

**Comment by warese32** [comment]
ЁБА***Й pastebin.com ну какого оно не работает сцу****а 
ну ппц блин 
Помогите уже разобраться в конце та концов 
https://pastebin.com/raw/LDYSkE2y вот url с ip как должно быть 
нет не работает ишибка индекс находился вне границ массива!
