### ISSUE TITLE
Помогите с Lime-RAT 

### ISSUE THREAD

**Issue by warese32** [NYAN-x-CAT/Lime-RAT#39]
Помогите уже разобраться в конце та концев
https://pastebin.com/raw/LDYSkE2y вот url с ip как должно быть 
нет не работает ошибка индекс находился вне границ массива !

**Comment by NYAN-x-CAT** [comment]
I don't understand Russian. Sorry. But watch the video on LimeRAT/MISC/Support

95.153.75.57:8989

**Comment by warese32** [comment]
спасибо за помощь но разобрался извините за беспокойство нужно было просто по раскинуть просто серым вещество))
