### ISSUE TITLE
Not a Issue, but a question :)

### ISSUE THREAD

**Issue by DataDrug** [NYAN-x-CAT/Lime-RAT#4]
Could you please point out where should the changes be made, both in the controller .sln and on the stub one ?

**Comment by NYAN-x-CAT** [comment]
I didn't understand. Sorry

**Comment by DataDrug** [comment]
Do we just need to compile the code as it is, or should changes be made on it ? adding LHOST, LPORT, etc ?

I'm just lost as how to modify them.
I've found the "%LHOST%" and "%LPORT"% in the configs, when I change it, should the "" stay or should they be removeD?

**Comment by NYAN-x-CAT** [comment]
I used Mono.Cecil library, so you don't need to change anything. The builder will change it for you.

**Comment by DataDrug** [comment]
So i just need to compile ? :O

**Comment by NYAN-x-CAT** [comment]
Yes. Just compile it.
