### ISSUE TITLE
hey,man~how should i setting this ip

### ISSUE THREAD

**Issue by jackhah** [NYAN-x-CAT/Lime-RAT#41]
I am chinese,please tell me what should i setting my pastebin text of ip and port,i have wacth your video ,but your video is test on local,i have try it,and it success,but when i test on my public computer,it can't receive a session.what's the problem.Looking fo
![2](https://user-images.githubusercontent.com/43500186/45958507-2ecb7a00-c04a-11e8-8477-c7dba00397db.png)
![3](https://user-images.githubusercontent.com/43500186/45958509-2f641080-c04a-11e8-8b69-4074481967c7.png)
![4](https://user-images.githubusercontent.com/43500186/45958510-2ffca700-c04a-11e8-9928-c6ee3cf0bf37.png)

rward to your reply.Very thankful~~~

**Comment by NYAN-x-CAT** [comment]
Hello @jackhah 

It means your IP is wrong. check http://checkip.dyndns.org/ to get your IP.

**Comment by R3verseCha0s** [comment]
is this port even possible?
