### ISSUE TITLE
The constructor does not work for windows server 2012 R2

### ISSUE THREAD

**Issue by sercoss** [NYAN-x-CAT/Lime-RAT#43]
Use the constructor, try it in windows 2012 R2 and it did not work, only all the modules in win 7

**Comment by sercoss** [comment]
is it works in windows server 2008!

**Comment by NYAN-x-CAT** [comment]
You means plugins? You need to install 2.0 framework, or compile the plugins to 4.0

**Comment by NYAN-x-CAT** [comment]
windows 2012 = Plugins 4.0
windows 2008 = Plugins 2.0
