### ISSUE TITLE
Help For Lime-Rat 

### ISSUE THREAD

**Issue by Deeptune** [NYAN-x-CAT/Lime-RAT#44]
help me please i open your rat but show me this error and i open my virus but not show my Pc on rat why???
help sorry my bad English 
please Make a Complete video using this rat 
https://i.imgur.com/xLft7Xz.png
https://i.imgur.com/JPlHJG7.png
check this images please replay me

**Comment by NYAN-x-CAT** [comment]
Hello @Deeptune 
I think I know the problem. you are using very old windows. I think you are using windows 7 first release. You didn't update it yet to SP1 or SP2.
However, You can update your explorer browser https://www.microsoft.com/en-us/windows/microsoft-edge
Or search for pastebin alternative websites that don't use https.

**Comment by Deeptune** [comment]
Not working please make a complete videos using this rat 
https://i.imgur.com/zSwc1lE.png
https://i.imgur.com/Ji4NSiB.png
https://i.imgur.com/1ul6W1C.png
Please Check Images

**Comment by NYAN-x-CAT** [comment]
Hello @Deeptune 

Did you watch the video on "LimeRAT\MISC\Supprt"?
Also, Did you port forwarding router and disable windows firewall?
