### ISSUE TITLE
need high privilege

### ISSUE THREAD

**Issue by hasanalizxc** [NYAN-x-CAT/Lime-RAT#45]
Dear nyan,

Hope you are fine. I read the readme and saw this.

http://prntscr.com/l13xqu

How can i change this setting from source code? I mean i want to make it ticked run as admin like this picture.

http://prntscr.com/l13y8f

OR

How can i change the source code for running that 2 options (http://prntscr.com/l13xqu) in non admin privielege mod.

Thanks.

**Comment by NYAN-x-CAT** [comment]
Hello @hasanalizxc 

You can run as admin using right click. http://prntscr.com/l159i1

Or modify the source code for "client" (_Right click -> Add -> New Item -> Manifest File_)
**replace** `<requestedExecutionLevel level="asInvoker" uiAccess="false" />`
**with** `<requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />`

**Comment by hasanalizxc** [comment]
Hello nyan,

Thanks for your reply and interest but you understood me wrong brother :) I mean how can disable run with admin priviliege. I want to use ransom (http://prntscr.com/l13xqu) but i won't run it by high privilege (admin rights). I want to use anti-kill feature (http://prntscr.com/l13xqu) without admin priviliege.

**Comment by NYAN-x-CAT** [comment]
@hasanalizxc 
You can't use anti-kill without admin

**Comment by hasanalizxc** [comment]
Ok i eliminated anti-kill. How can i change it to run without admin rights. I mean i will run it without admin rights but it will work with this way.

**Comment by hasanalizxc** [comment]
Noyan, you didn't answer but you closed the case?
