### ISSUE TITLE
Need Port FW?

### ISSUE THREAD

**Issue by hasanalizxc** [NYAN-x-CAT/Lime-RAT#46]
Dear Noyan,

Is this need port fw?

THanks.

**Comment by R3verseCha0s** [comment]
Yes, indeed as all rats do. If you need any help setting it up hit me up on my discord: Florid1995#4983

**Comment by hasanalizxc** [comment]
Thank you so much. Is this has anti-debug and anti-reverse feature?

**Comment by NYAN-x-CAT** [comment]
Hi @hasanalizxc  
You need port fw. and yes it has anti debug. you may need to check C_AntiVM for more details.

**Comment by hasanalizxc** [comment]
I appreciate you for quick replies. Thanks.
