### ISSUE TITLE
Will you add mining support for the new Fork?

### ISSUE THREAD

**Issue by Jh0nW1cK** [NYAN-x-CAT/Lime-RAT#47]
On October 18 the algorithm is changed to criptonight version 2, will launch a version of lime rat with the new POW?

**Comment by NYAN-x-CAT** [comment]
Hello @Jh0nW1cK 
I don't know about the algorithm updates, But I will keep an eye on it.

**Comment by Jh0nW1cK** [comment]
Hello @NYAN-x-CAT

https://github.com/xmrig/xmrig/issues/753

**Comment by Jh0nW1cK** [comment]
Thanks for the update in the new version
