### ISSUE TITLE
Port seems to be blocked error

### ISSUE THREAD

**Issue by alarin1** [NYAN-x-CAT/Lime-RAT#49]
I got this error that says that port xxxx seems to be blocked, even after adding to firewall exception.

But that port is open 100%, and firewall is off.

Any advice?

**Comment by R3verseCha0s** [comment]
Add me on discord and I will help you. @Florid1995#4983

**Comment by NYAN-x-CAT** [comment]
@alarin1 
I see, But did you try to run the client on your PC? just to test it.

**Comment by alarin1** [comment]
@NYAN-x-CAT 
I try, but it don`t works on my PC

**Comment by NYAN-x-CAT** [comment]
@alarin1  Make sure your port forwarding is valid. Also try to check your port here http://www.canyouseeme.org/

**Comment by alarin1** [comment]
@NYAN-x-CAT 
Confirmed that it is open on that site.
I`m testing this on freshly installed VM, without AV, and with Firewall off. On WIN7

**Comment by NYAN-x-CAT** [comment]
@alarin1 I see. Can you try it on windows 10? There is a bug that the client doesn't work freshly windows7, I already fix it but I will release the update later. For now, you need to update your browser from here https://www.microsoft.com/en-us/windows/microsoft-edge Or use windows 10.

**Comment by alarin1** [comment]
@NYAN-x-CAT 
Thanks man, i will try it on win 10.

**Comment by 0xOkita** [comment]
Confirmed bug, I changed port listening to 80 and it worked, but not for 443. Can you update no-ip dns in case pastebin is not going to work in the future please. Thank you. Im running on win 10

**Comment by NYAN-x-CAT** [comment]
@bin14101998 Yes the problem is the SSL protocol (only fresh windows 7) , I will release an update but not now.
