### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by suriya73** [NYAN-x-CAT/Lime-RAT#5]
> Use "Release" compiler in both solution
Execute "Server_0.4\Server_0.4\bin\Release\Lime Worm.exe"
Copy "Client_0.4\Client_0.4\bin\Release\Stub.exe", To "Server_0.4\Server_0.4\bin\Release\Stub\Stub.exe"

> 

just fallowed this steps, and tried to build WORM.exe but i dont see any option like build or how i can build it ??

Screenshot- 
[https://prnt.sc/itq9al](url)

**Comment by NYAN-x-CAT** [comment]
You are using virtualbox right? I tested on VMware and it's working just fine, but I will fix this bug in next update.

**Comment by suriya73** [comment]
yes its a vm (windows 7), 

will this works fine normally ??

**Comment by NYAN-x-CAT** [comment]
I didn't test it on virtualbox , I only tested it on real PC and VMware.
But I will fix this issue for virtualbox soon

**Comment by suriya73** [comment]
yeah i got you, 
but in my case im also using vmware 12 which is installed in Linux mint.

**Comment by NYAN-x-CAT** [comment]
I'm using latest vmware on windows 10 and it's woking 100% fine

**Comment by suriya73** [comment]
okay cool ..! let me test it on windows 10.
Thanks for the quick update.

**Comment by NYAN-x-CAT** [comment]
Just released a new update. https://github.com/NYAN-x-CAT/Lime-Worm/releases/tag/0.4.2A

Fixed VirtualBox bug

**Comment by suriya73** [comment]
awesome .! 

thanks bro.
