### ISSUE TITLE
lost servers when upgrading to a new version

### ISSUE THREAD

**Issue by Jh0nW1cK** [NYAN-x-CAT/Lime-RAT#52]
Hi @NYAN-x-CAT 
I have done 2 updates and in both I lost 25-30% of the servers.

**Comment by NYAN-x-CAT** [comment]
@Jh0nW1cK there are many reasons for this issue
But it's not a bug at all. And actually when you say 30% instead of 100% then I'm sure its not a bug.

**Comment by Jh0nW1cK** [comment]
@NYAN-x-CAT  I think that losing 30% in each update is not normal.
It is not something that usually happens in other RATs.

**Comment by NYAN-x-CAT** [comment]
@Jh0nW1cK As I said. There are so many reasons.
If you want a discussion about your issue please email or discord me.
This section is only for bugs.

**Comment by Jh0nW1cK** [comment]
You say there are many reasons, can you tell me 2 reasons? 
Can you also provide me your discord please?

**Comment by NYAN-x-CAT** [comment]
@Jh0nW1cK You can find all contact details under support section https://github.com/NYAN-x-CAT/Lime-RAT/blob/master/README.md
