### ISSUE TITLE
PORT CLOSED

### ISSUE THREAD

**Issue by adlan051** [NYAN-x-CAT/Lime-RAT#56]
Hello,
I can't figure out where is the error. 
LimeRAT says that the port is closed but it's actually opened, checked with conyouseemee and yougetsignal also added firewall rule to fully allow selected ports.
tryed with other RAT and they are working.
Lime works on LAN and localhost.

I'm stuck and don't know what I can try.

Thank you.

YouGetSignal
http://prntscr.com/lddfxd

Canyouseeme
http://prntscr.com/lddgco

_Sorry for my bad english, not my main language :)_

**Comment by NYAN-x-CAT** [comment]
Hello.
Try build a client and run it. See if it connect or not.

**Comment by adlan051** [comment]
Tried it, not working.
I'm gonna try some old releases.
............
Same error, Lime think ports are closed.
............
Is this normal?
http://prntscr.com/ldshy5

**Comment by m1cr0m4ch1n3** [comment]
if you have VPN service disable it then try running L-R again

**Comment by NYAN-x-CAT** [comment]
Download compiled version.
Read support folder "inside MISC folder"

**Comment by adlan051** [comment]
> if you have VPN service disable it then try running L-R again

Tried disabling VPN service, no success.

> Download compiled version.
> Read support folder "inside MISC folder"

There is only Guidance.html and Pastebin TUT, I use my own server with ips txt.

I'm gonna try on fresh installed windows 7 on VMware

**Comment by NYAN-x-CAT** [comment]
@adlan051  Well try pastebin first. it will work. then you can search for your issue on your vmware or server/domain

**Comment by adlan051** [comment]
> @adlan051 Well try pastebin first. it will work. then you can search for your issue on your vmware or server/domain

Tried pastebin, no luck. 
In the builder tab, when i press Check url with my txt file it works (L-R can read the ip from my site).
On fresh installed Win 7, port are still marked as closed.

I began to think that it could be my modem issue.
Will try to find another modem and try with it.

**Comment by m1cr0m4ch1n3** [comment]
lets get back to the basics.  have you checked and double checked your pastie/txt and made sure there arent any unwanted spaces, commas, semicolons or such?

**Comment by adlan051** [comment]
I did. When I check the url through RAT it says that is valid. 
But the rat doesn't see opened port. Ports are marked as closed but it's actually opened.

**Comment by NYAN-x-CAT** [comment]
https://github.com/NYAN-x-CAT/Lime-RAT/releases/download/v0.1.8.C/LimeRAT.v0.1.8.5C.zip

https://pastebin.com/raw/DDTVwwbu

Double check FW allow LR ports

**Comment by adlan051** [comment]
> https://github.com/NYAN-x-CAT/Lime-RAT/releases/download/v0.1.8.C/LimeRAT.v0.1.8.5C.zip
> 
> https://pastebin.com/raw/DDTVwwbu
> 
> Double check FW allow LR ports

Just checked. 
It works on Localhost and over LAN.
First checked with your pastebin url, it worked, 
then used txt file from my site, it worked on localhost and over LAN but when I entered my WAN, public IP it didn't connected.

**Comment by NYAN-x-CAT** [comment]
Then there is a problem with your ip.

**Comment by adlan051** [comment]
Thank you very much for your help.
I will try with other ip.

**Comment by Achilles29** [comment]
Have some problem. I’ve port forwarding the IP to my vps ip, the url check says valid. But port still closed and client didnt show up

**Comment by NYAN-x-CAT** [comment]
https://github.com/NYAN-x-CAT/Lime-RAT/releases/download/v0.1.8.C/LimeRAT.v0.1.8.5C.zip

https://pastebin.com/raw/DDTVwwbu

Double check FW allow LR ports
