### ISSUE TITLE
Please, add new options for my family

### ISSUE THREAD

**Issue by Abraham313** [NYAN-x-CAT/Lime-RAT#57]
Please, Add new options to protect my kids from objectionable activity.If you add website block feature and instantly  Clear cookies and delete logins.It will be great help for my nice and heavenly family.  Pardon me ,I do not know how to use github and where to write a request.But I need this useful rat to monitor my kids. Thanks for your philanthropic work.

**Comment by NYAN-x-CAT** [comment]
Hello @Abraham313 

I will definitely consider your suggestions

**Comment by Abraham313** [comment]
Thanks for your kind response.I will wait for your next version.I hope I can monitor my kids properly without hurting their unadulterated soft mind .
