### ISSUE TITLE
is ransomware working right now?

### ISSUE THREAD

**Issue by matorina22** [NYAN-x-CAT/Lime-RAT#59]
Hello the ransomware function is always stuck at Encryption in progress..., I don't know if this is normal or not, but it's already like that for quite long amount of time.
Is this supposed to be like that or not? 
Thanks

**Comment by Pablito89** [comment]
got the same problem

**Comment by Pablito89** [comment]
> Hello the ransomware function is always stuck at Encryption in progress..., I don't know if this is normal or not, but it's already like that for quite long amount of time.
> Is this supposed to be like that or not?
> Thanks

it worked for me after 15/20mins

**Comment by NYAN-x-CAT** [comment]
It depends on cpu and hdd. Should take about 10min to 1 hour

**Comment by matorina22** [comment]
why does it says Access to path Users\User\ is denied?
It has also been way more than 1 hour and its still saying the same, the PC has two hard disks and good CPU

**Comment by matorina22** [comment]
Still is an issue

**Comment by matorina22** [comment]
> It depends on cpu and hdd. Should take about 10min to 1 hour

why does it says Access to path Users\User\ is denied?
It has also been way more than 1 hour and its still saying the same, the PC has two hard disks and good CPU
