### ISSUE TITLE
Why is it connecting to a out side connect?

### ISSUE THREAD

**Issue by cyclo-techtwister** [NYAN-x-CAT/Lime-RAT#60]
It is establishing a active connection to this ip 104.20.208.21
Why would it need to do this? This seems insecure and may pose a threat, no?

**Comment by NYAN-x-CAT** [comment]
https://www.abuseipdb.com/whois/104.20.208.21

**Comment by cyclo-techtwister** [comment]
@NYAN-x-CAT well that answers that, thank you..
