### ISSUE TITLE
Password stealer doesnt work on Windows 7 Sp1 x64

### ISSUE THREAD

**Issue by cyclo-techtwister** [NYAN-x-CAT/Lime-RAT#61]
It may work on a 32bit system but not on a x64.. And yes there are passwords saved for testing purposes. Using Chrome and IE. Correct me if I am wrong but a 32bit process (client) can not retrieve pw using x64 .dll

**Comment by NYAN-x-CAT** [comment]
Please only use issue when you have a bug.
pwd stealer should work.

**Comment by cyclo-techtwister** [comment]
Should work? Not a clear answer. Since most OS installations are in x64 and your answer does not answer the question. Is it suppose to work on x64 or not?
