### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by cyclo-techtwister** [NYAN-x-CAT/Lime-RAT#62]
Built in reg edit would be very useful

remote command prompt for running shell scripts ect..

user mode root kit

password stealer for x64 systems

**Comment by NYAN-x-CAT** [comment]
This is a learning project. "You" should learn to add these features by yourself

**Comment by cyclo-techtwister** [comment]
@NYAN-x-CAT - OK, point taken. Thank you.
