### ISSUE TITLE
Problem with local port

### ISSUE THREAD

**Issue by anonymous11102** [NYAN-x-CAT/Lime-RAT#66]
Pastebin is automatically putting a space between 127.0.0.1: and whatever port. Attached is a picture. When clicking check, it keeps saying wrong format. Its the wrong format because pastbin adds a space. Pastebin may take too much time to fix this. So the best solution is make the program read it with a space also. 
![port picture](https://user-images.githubusercontent.com/45556144/49362981-3f751d80-f695-11e8-9050-c0c1b6b6805b.png)

**Comment by NYAN-x-CAT** [comment]
https://pastebin.com/4kXDzvyN

**Comment by anonymous11102** [comment]
I used that just now, and this is the error I got. That port is in my settings though. 
![new port image](https://user-images.githubusercontent.com/45556144/49365787-81559200-f69c-11e8-8935-74757771e3c7.png)

**Comment by NYAN-x-CAT** [comment]
Because 127 is not your real ip. Please check source code before posting anything.

**Comment by NYAN-x-CAT** [comment]
Because 127 is not your real ip. Please check source code before posting anything.

**Comment by anonymous11102** [comment]
it is my local ip, the same local Ip that everyone has when running it on themselves, like in your video. The error should be corrected so that it does not say it doesnt work. 127 should always work when testing on oneself.
