### ISSUE TITLE
Port showing closed, when it is open

### ISSUE THREAD

**Issue by anonymous11102** [NYAN-x-CAT/Lime-RAT#67]
Port is 100% open, but the program says it is closed. Can you see me indicates its open, port forward programs, also say udp and tcp is open. All av's disabled. In your youtube tutorial, when testing, it also did not show at the top that it was open, however you still were able to see your own pc. So its not able to know when it is open and when it is not.

**Comment by NYAN-x-CAT** [comment]
Ignore it.

**Comment by anonymous11102** [comment]
Yes but I'm asking if you can fix it?
