### ISSUE TITLE
Having issues

### ISSUE THREAD

**Issue by Tom342** [NYAN-x-CAT/Lime-RAT#68]
I have 2 issues at the moment
1. It says my port is closed but is clearly open (said to ignore it, but maybe its saying the truth?)
2. I cannot test on myself like said in different issue (Unless im doing something wrong)

EDIT: I have tried on VM and it doesn't work

**Comment by OpsecGuy** [comment]
1. idk
2. Make sure you unchecked 'anti vm' function.

**Comment by Tom342** [comment]
I have tried not on a VM (on my pc) and it didn't work :/ I think it's having connection issues? On quasar rat it works on my normal pc, if I run wires hark I can see it trying to connect, I have port forwarded so idk

**Comment by NYAN-x-CAT** [comment]
1-Use official release
https://github.com/NYAN-x-CAT/Lime-RAT/releases/tag/v0.1.9.0F

2-You can find some good answers from here
https://github.com/NYAN-x-CAT/Lime-RAT/issues?q=is%3Aissue+is%3Aclosed

**3-This is not a bug.**
