### ISSUE TITLE
Port closed

### ISSUE THREAD

**Issue by HenNeko** [NYAN-x-CAT/Lime-RAT#69]
Hi there! I have an issue with ports.
![image](https://user-images.githubusercontent.com/38375337/49685047-ba06c880-faed-11e8-9193-a65060b8252d.png)
And there is no problem with brandmauer, all ports for incoming connections for Lime are open, but i still can't figure whats going on.
And it was working a day before, but now all ports are closed and i lost "my" virtual machine.
Win 7, using your build.

**Comment by NYAN-x-CAT** [comment]
Try http://www.mediafire.com/file/htwcueseubgd4ww/Lime-Port-Checker.zip/file
