### ISSUE TITLE
Problem with pastebin link

### ISSUE THREAD

**Issue by imrory** [NYAN-x-CAT/Lime-RAT#7]
Sometimes when i click check url, it drops an error.
I fixed on the src anyway.
If you need help devolping let me know

**Comment by NYAN-x-CAT** [comment]
Thanks for your feedback. You mean there is a problem with Regular Expressions ?

**Comment by imrory** [comment]
Yes sr! where can i contact you

**Comment by NYAN-x-CAT** [comment]
You can use my email. But it's better to share your point or code here so people can see it
