### ISSUE TITLE
LimeRAT v0.1.9.1  Crashed and Fix client Save Option

### ISSUE THREAD

**Issue by David200018** [NYAN-x-CAT/Lime-RAT#70]
1. Your Released Version LimeRAT v0.1.9.1 has been crashed When it is loading IP and Port . Version LimeRAT v0.1.8.5C is still most powerful and stable yet I have not find anything wrong in this version.
2.When we click on build button it shows just " Yes  "  or " No "  Options  and create a file Named "  NEW-CLIENT.exe " But , I consider myself that you should also add where to save and what name will be keep to the stub. 

3. And One more options Should be added that Show Version number on the RAT  Windows .
4.  One of My question If I reinstall My Windows Will I get back All of My Files What was encrypted by Lime  ransomware ?  

Thanks

**Comment by NYAN-x-CAT** [comment]
1- It's still a beta version but it's working just fine. try to use the compiled version.

2- Nice idea, but you still can check from "about"

3- no

**Comment by David200018** [comment]
Thanks for Quick Reply But I think it's also Important What I made mistake in numbering 

When we click on build button it shows just " Yes " or " No " Options and create a file Named " NEW-CLIENT.exe " But , I consider myself that you should also add where to save and what name will be keep to the stub.

**Comment by NYAN-x-CAT** [comment]
This option can be changed using the source code. that's why I released the source code so you can modify it.

**Comment by David200018** [comment]
I also try  to add some more options in my free time .But You should do this for a little improvement of your nice learning program as I think .

Best wishes to you 
Thanks
