### ISSUE TITLE
System Details reported wrong information

### ISSUE THREAD

**Issue by cyclo-techtwister** [NYAN-x-CAT/Lime-RAT#71]
System Details detects and reports back incorrect data. Testing both Client and Server on a x64 Windows 7 OS. Says the Windows Architecture is x86 which the OS is not it is a 64bit system. Also Does not grab OS Product key. Is this simply because the client is a 32bit process? If so just close this issue, thank you..

**Comment by NYAN-x-CAT** [comment]
Yes, I know these issues and will fix it later. thanks for feedback

**Comment by cyclo-techtwister** [comment]
OK, You're Welcome..
