### ISSUE TITLE
dns support?

### ISSUE THREAD

**Issue by gx1000** [NYAN-x-CAT/Lime-RAT#77]
Could you possibly add dns support? 

or how could one go about editing the code to allow for website.com:port

**Comment by enkianu** [comment]
It's possible using Pastebin or similar service that allows direct "RAW" text acess. Simply use it as you've suggested E.g: **maga.no-ip.org:8989**

**Comment by NYAN-x-CAT** [comment]
yes, you can use maga.no-ip.org:8989

**Comment by gx1000** [comment]
Im using a freenom dns, Would anything need to be changed in the code or or simply change ip:port to website.tk:port

**Comment by gx1000** [comment]
Nevermind, It works
