### ISSUE TITLE
LimeRAT deleted itself after a few seconds when I ran it in administrator mode

### ISSUE THREAD

**Issue by zix3r** [NYAN-x-CAT/Lime-RAT#79]
So basically I ran it in admin mode, made a client, and after a few seconds it closed and deleted it self, any suggestions?

**Comment by NYAN-x-CAT** [comment]
anti vm

**Comment by zix3r** [comment]
i wasnt running it in a vm

**Comment by zix3r** [comment]
i didnt even run the rat

**Comment by zix3r** [comment]
i mean the WHOLE LimeRAT program deleted it self.

**Comment by zix3r** [comment]
not the client

**Comment by NYAN-x-CAT** [comment]
It's your AV or windows defender.
