### ISSUE TITLE
cannot set ip/listen to localhost

### ISSUE THREAD

**Issue by syee47** [NYAN-x-CAT/Lime-RAT#81]
in S_functions.vb 
`If S_Settings.IP = String.Empty Then
                Dim response As Net.WebResponse = Net.WebRequest.Create("http://checkip.dyndns.org/").GetResponse()`

cannot set listening ip it set external WAN ip only. also in the builder, there is only pastbin url field. include a field for hostname/ip

**Comment by NYAN-x-CAT** [comment]
You have the source code. Edit whatever you want. It's just a simple project. It's not an official RAT.
Edit pastebin with YOUR-LAN:YOUR-IP
