### ISSUE TITLE
Minor issue with the connected client count.

### ISSUE THREAD

**Issue by ghost** [NYAN-x-CAT/Lime-RAT#84]
Hello.The problem is in the latest version.The only issue is that it shows offline clients as if they are online, on the counter in the lower left corner in the main form. Thanks.

**Comment by NYAN-x-CAT** [comment]
Thanks for your feedback. I will check it later.

**Comment by NYAN-x-CAT** [comment]
@AntINFINAit  Fixed. Thanks for your feedback
