### ISSUE TITLE
Malware detected, fuckyourself

### ISSUE THREAD

**Issue by fuckyourselfd** [NYAN-x-CAT/Lime-RAT#85]
motherfucker
use a sandbox and see for your selfe, wait a time and you see one process open, load and close alone, if you exec normal this shit create a folder in program file with trusted permission(Internet Explorer) and exec te persistence process, don't download this program of this motherfucker.

**Comment by fuckyourselfd** [comment]
i hope your mother give a cancer and tour fother died

**Comment by Hostah** [comment]
> i hope your mother give a cancer and your father dies

What if they are already dead?

**Comment by fuckyourselfd** [comment]
I'm going to hell to fuck them ass

**Comment by NYAN-x-CAT** [comment]
Hmmm its hard to understand but my best guess that he downloaded a backdoored LimeRAT from YouTube or google. Sorry man but next time only download from my GitHub.
