### ISSUE TITLE
No Access to internet at Windows 10 fresh system.

### ISSUE THREAD

**Issue by UN5T48L3** [NYAN-x-CAT/Lime-RAT#88]
Hello NYAN-x-CAT,

I've done everything correctly, but still cant able to access through the program.
![limerats](https://user-images.githubusercontent.com/39417235/51224860-f1705c80-1958-11e9-84ae-4f94a6a98f81.png)

**Comment by NYAN-x-CAT** [comment]
@UN5T48L3 https://www.tomshardware.com/news/how-to-open-firewall-ports-in-windows-10,36451.html

**Comment by UN5T48L3** [comment]
@NYAN-x-CAT Firewall rules already has been added and even I disabled my firewall. But still same.

**Comment by UN5T48L3** [comment]
More informations about this issue;

Host machine: MacOS.
I'm using VirtualBox btw. Either I set NAT or bridge, did not work to get a stable connection. I caught a connection 1 time when I set on DMZ from my router.

Another problem is you have to allow any raw link instead of pastebin. I mean, Pastebin is blocked in Turkey, so we have put different service like paste.ee.
Also people can host their raw text file in their servers to put link.

This is just an idea to get this RAT better.

Regards,

**Comment by NYAN-x-CAT** [comment]
@UN5T48L3 
You can use any RAW such as ghostbin.com gist.github.com
Also, you can upload a text file to your domain.
I think the problem is from your router.
