### ISSUE TITLE
Password Recovery unsupported on some browsers

### ISSUE THREAD

**Issue by enkianu** [NYAN-x-CAT/Lime-RAT#89]
Hi M8,
The job was well done in this new release. 
However, I've noticed that the password recovery plugin doesn't seem to work with **FIREFOX DEVELOPER EDITION** and **OPERA BROWSERS**. 
Seem to only work with Chrome and IE

**Comment by NYAN-x-CAT** [comment]
@enkianu Because It's outdated password recovery.
